name: Monthly API Request

on:
  schedule:
    - cron: '0 6 1 * *'
  workflow_dispatch:

jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Production Environment
      run: |
        if [ "${{ secrets.ENVIRONMENT }}" = "production" ]; then
          curl -X GET "https://expense-manager-pink.vercel.app/$API_ENDPOINT"
        else
          echo "Skipping action in non-production environment."
        fi
      env:
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
