name: Monthly API Request

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Request generate accs
      run: |
          echo "Generating..."
          curl -X GET "https://expense-manager-pink.vercel.app/$API_ENDPOINT"
      env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
