name: Monthly API Request

on:
  schedule:
    - cron: '0 6 1 * *'

jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Request generate accs
      run: |
          echo "Creating..."
          curl -X POST "https://expense-manager-pink.vercel.app/$API_ENDPOINT"
      env:
        API_ENDPOINT: ${{ secrets.MONTH_ACC_API_ENDPOINT }}
